package com.example.programmatic

data class PropertiesXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX(
    val paragraphStyle: ParagraphStyleXXX,
    val paragraphStyleSuggestionState: ParagraphStyleSuggestionStateXX
)